### PR TITLE
Update 60_cardinality.asciidoc

### PR DESCRIPTION
**Pull request by mcascallares**
Fix broken link

### CODE REVIEW

**Comment by suzuki** [comment]
I found a same problem just now.
Thank you fix !

**Comment by polyfractal** [comment]
Looks like the link changed again.  There is now an extra slash by `en`:  http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/40671.pdf

Would you mind updating your PR and I'll merge it?

**Comment by mcascallares** [comment]
Updated with two '/', thanks for the heads up.
BTW it is hard to believe that Google does not put some HTTP301 when changing their URLs

**Comment by polyfractal** [comment]
I know, right?  Shame google, shame!

Thanks for the update :)

**Pull request merged**
