### PR TITLE
Using a dot instead of a comma as separator

### PR DESCRIPTION
**Pull request by lefloh**

### CODE REVIEW

**Comment by polyfractal** [comment]
++.  Can you [sign the CLA](https://www.elastic.co/contributor-agreement/) so we can get this merged?

**Comment by lefloh** [comment]
done.

**Comment by lefloh** [comment]
Any problems with merging this?

**Comment by polyfractal** [comment]
Oh my goodness, nothing wrong, sorry!  This appears to have been buried in the sands of time.

Sorry about that!

**Pull request merged**
