### PR TITLE
Update 30_Tutorial_Search.asciidoc

### PR DESCRIPTION
**Pull request by thewhitetulip**
GET doesn't work, curl -GET works

### CODE REVIEW

**Comment by dadoonet** [comment]
It's the syntax for the CONSOLE (formerly SENSE).

**Comment by thewhitetulip** [comment]
Can we mention it there? I might have missed :-D

**Comment by dadoonet** [comment]
I think you missed the last part of this page probably: https://www.elastic.co/guide/en/elasticsearch/guide/current/_talking_to_elasticsearch.html

**Comment by thewhitetulip** [comment]
Yes, overlooked it. Was in a hurry, I think we can still put it in bold or make it a section

**Pull request closed without merging**
