### PR TITLE
Fix broken query for Elasticseach 2.2

### PR DESCRIPTION
**Pull request by tylerjryan**
The sample query provided has a few issues that result in errors if someone tries to copy/paste and use it as a query clause. 

On the inner "bool" clause, " the "must" and "must_not" clauses were both missing an inner "match" parameter. 

Lastly, "minimum_should_match" is no longer correct syntax, and should be replaced by "minimum_number_should_match".

### CODE REVIEW

**Comment by polyfractal** [comment]
Awesome, thanks for the fixes!  Would you mind signing the [Elastic CLA](http://www.elasticsearch.org/contributor-agreement/) so I can merge this?

**Comment by tylerjryan** [comment]
signed!

**Comment by zanona** [comment]
Perhaps preserving the coding style would help analysing the diff and quickly spot the differences? _(i.e: indent 4, instead 2)_

**Comment by tylerjryan** [comment]
Updated to match coding style, and now the diff looks much better.

**Comment by polyfractal** [comment]
Woo, thanks!  Sorry for the delay, was out in SF for elasticon, then a long team meeting, then unburying my inbox :)

Quick question: did you have a source stating that "minimum_should_match" is no longer supported?  I see that it's still in the code (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/BoolQueryParser.java#L41), but perhaps there is a ticket somewhere that I'm missing which says we plan to deprecate?  I'll ask around too :)

**Comment by tylerjryan** [comment]
Welcome back!

Looks like they both work! In Sense, the autocomplete only suggests "minimum_number_should_match". So maybe the plan is to transition to using only "minimum_number_should_match" in the future? I haven't actually seen this explicitly stated anywhere though. If you'd like, I can change the query to use the "minimum_should_match" instead.

**Comment by polyfractal** [comment]
Ah ok, could very well be the intention.  

@clintongormley do you happen to know if `"minimum_number_should_match"` will become the One True Way in the future?

**Comment by clintongormley** [comment]
Definitely not :)  I didn't even know it existed

**Comment by tylerjryan** [comment]
so should we change that line back then?

**Comment by polyfractal** [comment]
@tylerjryan Yeah, let's put that back to `minimum_should_match`, then this should be good to merge.  Sorry for the hassle, I should have noticed that upfront at the beginning

**Comment by polyfractal** [comment]
Thanks @tylerjryan!  Merging

**Pull request merged**
