### PR TITLE
Fixes analyze "Black-cats" output to match text

### PR DESCRIPTION
**Pull request by cscorley**

### CODE REVIEW

**Comment by polyfractal** [comment]
Hm, perhaps this is just worded/displayed poorly?  

The example is actually correct: it's demonstrating that the same text analyzes in two different ways based on the underlying field (in this case, `tweet` vs `tag`, which have different analyzers)

**Comment by cscorley** [comment]
Woof, you're right. I totally mixed the two examples up. Thought it was strange.

**Comment by cscorley** [comment]
Wait, no, *rubs eyes*

The `tweet` field is processed using the `english` analyzer, does that not tokenize and stem? The text following the example it produces two terms: `black` and `cat`, while the (original example) shows `Black-cats` for both tag and text.

**Comment by cscorley** [comment]
Got it.  Got confused on passing data in to a GET request.  Thanks!

**Pull request closed without merging**
