### PR TITLE
Update 30_Tutorial_Search.asciidoc

### PR DESCRIPTION
**Pull request by brianjester**
Thanks for the Pull Request!  We really appreciate your help and contribution!

Before you submit the PR, have you signed Contributor License Agreement: https://www.elastic.co/contributor-agreement/ ?

PR's (no matter how small) cannot be merged until the CLA has been signed.  
It only needs to be signed once, however. Thanks!

The More-Complicated Searches script "30_Query_DSL.json" didn't parse when using "sense" with square brackets "[]", but did when I swapped them with curly braces "{}".

### CODE REVIEW

**Comment by polyfractal** [comment]
Oh, I see.  So that'll work, but the more common convention is to use `must` as an array since there can be many clauses.  My the root problem is that the `match` clause must be wrapped as an object, like:

```
"must": [
  {
    "match" : {
      "last_name" : "smith" (1)
    }
  }
],
```

Do you want to make the change?  If yes, you'll need to[sign the CLA](https://www.elastic.co/contributor-agreement/) too, so I can merge it.  Thanks!

**Comment by brianjester** [comment]
@polyfractal CLA Signed!

**Comment by polyfractal** [comment]
Thanks!  Would you mind updating the syntax to array + object: `[ { ... } ]`  ?

**Comment by brianjester** [comment]
@polyfractal At this point in the tutorial the query refuses to execute in Sense when it's `[ { ... } ]` but works when it's `{ { ... } }`

**Comment by polyfractal** [comment]
I'm not sure tbh, it *should* work.  But the tutorial has been resolved with the simpler syntax you suggested, via #533.  Thanks!

**Pull request closed without merging**
