### PR TITLE
There are not 6 nodes before this section; there are 6 shards. There …

### PR DESCRIPTION
**Pull request by theredpea**
Thanks for the Pull Request!  We really appreciate your help and contribution!

Before you submit the PR, have you signed Contributor License Agreement: https://www.elastic.co/contributor-agreement/ ?

PR's (no matter how small) cannot be merged until the CLA has been signed.  
It only needs to be signed once, however. Thanks!

…are not >6 nodes after this section; there are > 6 shards.

### CODE REVIEW

**Comment by polyfractal** [comment]
This is correct how it's currently worded.  Shards in ES are the atomic unit of distribution, which can be moved around the cluster.  So if you have six shards, you can spread those to at most six different nodes.  If you add a 7th node, it won't receive any shards because a shard cannot be split.

So in context of that chapter, it's asking the question of what to do about that 7th node.  The text explains that you can't add more primaries -- since those are fixed at index creation -- but you can add replicas.  Those replicas can then leverage the 7th node.

By adding more shards, you allow yourself to scale to more nodes.

**Comment by theredpea** [comment]
Yep, I understood later. Could not figure out how to undo pull request.
Thank you.

**Comment by polyfractal** [comment]
No problem at all!  I don't think there is a way to delete PRs anyhow, just close them.  Thanks anyway for the PR, we appreciate all PRs.  The community has provided a ton of great edits/changes which we overlooked. :)

(Hopefully this goes through, Github is having some troubles at the moment)

**Comment by clintongormley** [comment]
thanks for the PR @theredpea but nodes is intended here.  "you have six shards, so you can put each one on a single node to have six nodes.  but what if you want MORE than six nodes?"

thanks anyway

**Comment by clintongormley** [comment]
Whoops - looks like github is going wonky - i thought this was new

**Pull request closed without merging**
