### PR TITLE
Update 60_Sorting_and_collations.asciidoc

### PR DESCRIPTION
**Pull request by shubham391**
Fix typo "insentive" for "insensitive", and letter case in word "Böhm" used as example.

### CODE REVIEW

**Comment by shubham391** [comment]
Not sure why CLA check failed. I signed and verified (from email) before creating the PR. Anything else needs to be done ?

**Comment by karmi** [comment]
Hi @shubham391, I have re-triggered the check and it now passes -- you probably commented too soon after signing, so our systems haven't synced yet.

**Comment by shubham391** [comment]
Thanks @karmi . Yes, I did create the PR right after the signing process.

**Comment by polyfractal** [comment]
Thanks, merging!

**Pull request merged**
