### PR TITLE
fix Elastisearch typo

### PR DESCRIPTION
**Pull request by m-khl**

### CODE REVIEW

**Comment by polyfractal** [comment]
Thanks!  Would you mind [Signing the CLA](https://www.elastic.co/contributor-agreement/) so that we can merge this?

**Comment by m-khl** [comment]
just did it

**Comment by m-khl** [comment]
just did it

**Comment by m-khl** [comment]
@polyfractal, I signed CLA, would you mind to merge #613 ?

**Comment by polyfractal** [comment]
Oops, sorry, fell through my inbox.  Checked in the DB and you're good to go, thanks!

**Pull request merged**
